name: Env Check Test
run-name: ${{ github.actor }} is testing out GitHub Actions ðŸš€
on: [workflow_dispatch]
jobs:
  external-job:
    uses: Nordix/nsm-github/.github/workflows/env-check.yml@arp-env-checker
